// Generated by Skyramp v1.3.37 on 2026-08-09 04:02:34.262893315 +0000 UTC m=+384.252704178
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/admin_users_last_login_column_render_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("button", { name: "Logout" }).waitFor({ state: "visible" });

    await page.goto("http://localhost:9000/admin/manage/users");
    await page.waitForLoadState("networkidle");
    const adminRow = page.getByRole("row", { name: /admin@mealie.test/ });
    await adminRow.waitFor({ state: "visible" });
    const lastLoginCell = adminRow.getByRole("cell").nth(8);
    await expect(lastLoginCell).not.toHaveText("");

    expect(pageErrors).toHaveLength(0);
});
