// Generated by Skyramp v1.3.29 on 2026-06-25 21:18:15.16857553 +0000 UTC m=+530.831010567
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output admin_users_row_click.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/admin_users_row_click_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(163000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/admin/manage/users");
    await page.waitForLoadState('networkidle');
    await page.locator("main").getByRole("row", { name: "bd47272c-7416-4050-b846-" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("main").getByRole("row", { name: "bd47272c-7416-4050-b846-" }).click();
    await expect(page).toHaveURL(/\/admin\/manage\/users\//);
    await expect(page.getByRole("heading", { name: "Admin User Management" })).toHaveText("Admin User Management");
    await expect(page.getByRole("textbox", { name: "User Name" })).toHaveValue("admin");
    await expect(page.getByRole("textbox", { name: "Full Name" })).toHaveValue("Change Me");
    await expect(page.getByRole("textbox", { name: "Email" })).toHaveValue("admin@mealie.test");
    expect(errors).toHaveLength(0);
});
