// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC m=+420.000000000
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output api_tokens_page.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/api_tokens_page_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(270000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // navigate straight to the self-contained API-tokens settings page
    await page.goto("http://localhost:9000/user/profile/api-tokens");
    await page.waitForTimeout(3000);

    // page title anchors that we are on the API-tokens page
    await expect(page.getByText("API Tokens", { exact: false }).first()).toBeVisible();

    // create-token form: the token name field
    const nameField = page.getByLabel("Token Name");
    await expect(nameField).toBeVisible();
    await nameField.fill("ci-token");

    // Generate button becomes enabled once a name is typed
    const generateBtn = page.getByRole("button", { name: "Generate" });
    await expect(generateBtn).toBeEnabled();

    // active-tokens section heading is present
    await expect(page.getByText("Active Tokens", { exact: false })).toBeVisible();

    expect(errors).toHaveLength(0);
});
