// Generated by Skyramp v1.3.29 on 2026-06-25 21:11:41.633130561 +0000 UTC m=+405.450617875
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output api_tokens_route_404.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/api_tokens_route_404_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(146000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/user/profile/api-tokens");
    await page.waitForSelector("text=404");
    await expect(page).toHaveURL(/user\/profile\/api-tokens/);
    await expect(page.getByRole("heading", { name: "404" })).toHaveText("404");
    await expect(page.getByRole("paragraph")).toHaveText("Page not found: /user/profile/api-tokens");

    expect(errors).toHaveLength(0);
});
