// Generated by Skyramp v1.3.37 on 2026-08-09 04:09:00.481622756 +0000 UTC m=+813.556257613
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output auto_form_field_testid.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/auto_form_field_testid_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(84000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForSelector("text=Create");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await expect(page.getByRole("textbox", { name: "Name" })).toBeVisible();
    await page.evaluate(() => {
  const nameField = document.querySelector('[data-testid="group-data-field-name"]');
  const colorField = document.querySelector('[data-testid="group-data-field-color"]');
  const dialog = document.querySelector('[data-testid="group-data-dialog"]');
  return {
    nameFieldPresent: !!nameField,
    colorFieldPresent: !!colorField,
    dialogPresent: !!dialog,
    dialogDataState: dialog ? dialog.getAttribute('data-state') : null
  };
});
    const nameFieldTestId = await page.evaluate(() => !!document.querySelector('[data-testid="group-data-field-name"]'));
    expect(nameFieldTestId).toBe(true);
    const dialogTestId = await page.evaluate(() => !!document.querySelector('[data-testid="group-data-dialog"]'));
    expect(dialogTestId).toBe(true);

    expect(errors).toHaveLength(0);
});
