// Generated by Skyramp v1.3.29 on 2026-06-25 21:19:34.889409701 +0000 UTC m=+589.560294072
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output base_dialog_cancel_dismiss.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_dialog_cancel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(102000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/shopping-lists");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/shopping-lists");
    await page.waitForSelector("text=Create");
    await page.goto("http://localhost:9000/shopping-lists?disableRedirect=true");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("button", { name: "Cancel" })).toHaveCount(0);
    await expect(page.getByRole("main").getByRole("button", { name: "Create" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
