// Generated by Skyramp v1.3.37 on 2026-08-09 04:07:04.73239311 +0000 UTC m=+732.990786965
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output base_dialog_data_testid.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/base_dialog_data_testid_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(994000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/units");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await expect(page.getByTestId("base-dialog")).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(page.getByRole("main").getByRole("button", { name: "Create" })).toBeFocused();
    expect(errors).toHaveLength(0);
});
