// Generated by Skyramp v1.3.29 on 2026-06-25 21:19:32.708614121 +0000 UTC m=+587.379498492
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output base_dialog_shopping_list_create.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_create_dialog_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(706000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/shopping-lists?disableRedirect=true");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:9000/login");
    await page.goto("http://localhost:9000/shopping-lists?disableRedirect=true");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "New List" }).fill("Skyramp Test List");
    await expect(page.getByRole("textbox", { name: "New List" })).toHaveValue("Skyramp Test List");
    await page.getByRole("dialog").getByRole("button", { name: "Create" }).click();
    await expect(page).toHaveURL(/\/shopping-lists\//);
    await expect(page.getByRole("heading", { name: "Skyramp Test List" })).toHaveText("Skyramp Test List");
    expect(errors).toHaveLength(0);
});
