// Generated by Skyramp v1.3.29 on 2026-06-25 16:14:22.76485052 +0000 UTC m=+581.719317585
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_delete_happy_path.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/bulk_delete_happy_path_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(720000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/labels");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "TestLabel-BulkDelete-1"};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/groups/labels**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest1: Record<string, any> = {"name": "TestLabel-BulkDelete-2"};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest1, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/groups/labels**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("row")).toHaveCount(3);

    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.getByRole("listitem").filter({ hasText: "Delete" }).click();
    await expect(page.getByTestId("bulk-rollup-header")).toContainText("0 of 2 succeeded");
    await expect(page.getByRole("button", { name: "Confirm" })).toBeVisible();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/groups/labels/**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response2 = await responsePromise2;

    expect(response2.status()).toBe(204);
    await expect(page.getByRole("button", { name: "Confirm" })).not.toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(1);
    await expect(page.getByRole("cell", { name: "No data available" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
