// Generated by Skyramp v1.3.29 on 2026-06-25 16:20:45.689333191 +0000 UTC m=+964.643800276
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_delete_dialog_cancel.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/bulk_delete_dialog_cancel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(674000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.locator("main").getByRole("checkbox", { name: "Select row" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("row")).toHaveCount(2);
    await page.locator("main").getByRole("checkbox", { name: "Select row" }).click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.getByRole("listitem").filter({ hasText: "Delete" }).click();
    await expect(page.getByTestId("bulk-rollup-header")).toContainText("0 of 1 succeeded");
    await expect(page.getByRole("button", { name: "Confirm" })).toBeVisible();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("button", { name: "Confirm" })).not.toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "TestLabel-BulkDelete-1" })).toHaveText("TestLabel-BulkDelete-1");
    expect(pageErrors).toHaveLength(0);
});
