// Generated by Skyramp v1.3.29 on 2026-06-25
// Tests the per-row data-state attribute and bulk-rollup-header added in this PR

import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 20000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(720000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    page.setDefaultTimeout(pageTimeout);
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "Name" }).fill("TestLabel-RowState");
    await page.waitForTimeout(1500);
    const createResp = page.waitForResponse("**/api/groups/labels**");
    await page.getByRole("button", { name: "Confirm" }).click();
    await createResp;
    await page.waitForTimeout(2000);

    await page.locator("main").getByRole("checkbox", { name: "Select all" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.getByRole("listitem").filter({ hasText: "Delete" }).click();

    await expect(page.getByTestId("bulk-rollup-header")).toContainText("succeeded");
    await expect(page.getByTestId("bulk-delete-dialog")).toBeVisible();
    await expect(page.getByRole("button", { name: "Confirm" })).toBeVisible();

    await page.getByRole("button", { name: "Confirm" }).click();
    await page.waitForTimeout(3000);

    await expect(page.getByRole("button", { name: "Confirm" })).not.toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(1);
    expect(pageErrors).toHaveLength(0);
});
