// Generated by Skyramp v1.3.29 on 2026-06-25 07:24:32.488131719 +0000 UTC m=+564.152032883
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cookbook_grid_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/cookbook_grid_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/cookbooks");
    await expect(page).toHaveURL(/\/g\/home\/cookbooks/);
    await expect(page.getByRole('heading', { name: 'Cookbooks', exact: true })).toHaveText('Cookbooks');
    expect(errors).toHaveLength(0);
});
