// Generated by Skyramp v1.3.37 on 2026-08-09 04:06:05.316385248 +0000 UTC m=+630.433947735
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output crudtable_category_row_id.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/crudtable_category_row_id_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1027000);

    const errors: Error[] = [];

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/categories");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:9000/group/data/categories/");

    const playwrightRequest0: Record<string, any> = {"name": "TestCategory"};

    const existingCategoryRow = page.getByRole("row", { name: getValue(playwrightRequest0, "name") });
    if (!await existingCategoryRow.isVisible().catch(() => false)) {
        await page.getByRole("main").getByRole("button", { name: "Create" }).click();

        await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
        // Wait to finish any potential hydration
        await page.waitForTimeout(1500);
        const responsePromise0 = page.waitForResponse("**/api/organizers/categories**");
        await page.getByRole("button", { name: "Confirm" }).click();
        const response0 = await responsePromise0;
        expect(response0.status()).toBe(201);

        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await expect(page.locator('tr[data-row-id]').first()).toBeVisible();
    await expect(page.locator('tr[data-row-id]').first()).toHaveAttribute('data-row-id', /.+/);
    await expect(page.getByText("1-1 of")).toContainText("1-1 of 1");

    expect(errors).toHaveLength(0);
});
