// Generated by Skyramp v1.3.29 on 2026-06-25 21:24:05.746604554 +0000 UTC m=+576.393216524
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output crud_table_data_selector.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/crud_table_data_selector_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(103000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("button", { name: "Select Data" }).click();
    await page.getByRole("link", { name: "Units" }).click();
    await expect(page).toHaveURL(/\/group\/data\/units/);
    await expect(page.getByRole("heading", { name: "Data Management" })).toHaveText("Data Management");
    expect(errors).toHaveLength(0);
});
