// Generated by Skyramp v1.3.29 on 2026-06-25 07:30:46.840789914 +0000 UTC m=+657.834413857
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output crud_table_genuinely_empty.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/crud_table_genuinely_empty_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(190000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("textbox", { name: "Search" }).fill("zzzxxx");
    await expect(page.getByRole("textbox", { name: "Search" })).toHaveValue("zzzxxx");
    await expect(page.getByRole("cell", { name: "general.no-data" })).toBeVisible();
    await expect(page.getByTestId("crud-search-no-match")).not.toBeVisible();
    expect(errors).toHaveLength(0);
});
