// Generated by Skyramp v1.3.29 on 2026-06-25 21:24:04.739021635 +0000 UTC m=+575.385633605
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output crud_table_label_create.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/crud_table_label_create_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(204000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "Name" }).fill("TestLabel-2026");
    await page.getByRole("button", { name: "Confirm" }).click();
    await page.getByRole("cell", { name: "TestLabel-" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("cell", { name: "TestLabel-" })).toContainText("TestLabel-2026");
    await expect(page.getByText("1-1 of")).toContainText("1-1 of 1");
    await expect(page.getByRole("row")).toHaveCount(2);
    expect(errors).toHaveLength(0);
});
