// Generated by Skyramp v1.3.29 on 2026-06-25 07:37:51.403276694 +0000 UTC m=+420.194310065
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output default_layout_cookbooks.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/default_layout_cookbooks_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();

    await expect(page).toHaveURL(/\/g\/home/);
    await expect(page.locator('[data-breakpoint]')).toHaveAttribute('data-breakpoint', 'desktop');

    await page.getByRole("link", { name: "Cookbooks" }).click();

    await expect(page).toHaveURL(/\/cookbooks/);
    expect(errors).toHaveLength(0);
});
