// Generated by Skyramp v1.3.37 on 2026-08-09 04:07:53.594813241 +0000 UTC m=+784.858689792
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dropzone_idle_state.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/dropzone_idle_state_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(775000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Idempotent setup: navigate to recipe edit page if it already exists
    const existingRecipe = page.getByRole('link', { name: 'Test Drop Zone Recipe' });
    if (await existingRecipe.isVisible().catch(() => false)) {
        await page.goto("http://localhost:9000/g/home/r/test-drop-zone-recipe?edit=true");
    } else {
        await page.getByRole("button", { exact: true, name: "Create" }).click();
        await page.getByRole("link", { name: "Create Create a recipe" }).click();

        const playwrightRequest0: Record<string, any> = {"name": "Test Drop Zone Recipe"};

        await page.getByRole("textbox", { name: "Recipe Name" }).fill(getValue(playwrightRequest0, "name"));
        // Wait to finish any potential hydration
        await page.waitForTimeout(1500);
        const responsePromise0 = page.waitForResponse("**/api/recipes**");
        await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
        const response0 = await responsePromise0;
        expect(response0.status()).toBe(201);

        // Wait for network activities to finish
        await page.waitForTimeout(10000);
    }

    await page.waitForURL("**/g/home/r/test-drop-zone-recipe**");
    await page.waitForSelector("text=Instructions");
    await expect(page.getByRole("heading", { name: "Instructions" })).toHaveText("Instructions");
    await expect(page.getByText("Attach images by dragging &").first()).toContainText("Attach images by dragging");
    await expect(page.getByRole("button", { name: "Save" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
