// Generated by Skyramp v1.3.37 on 2026-08-09 04:10:51.559816195 +0000 UTC m=+962.823692736
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dropzone_add_step.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/dropzone_add_step_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(75000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.getByRole("textbox", { name: "Email or Username" }).fill("admin@mealie.test");
    await page.getByRole("textbox", { name: "Password" }).fill("MyPassword");
    await page.locator("main").getByRole("button", { name: "Login" }).click();
    await page.waitForURL("**/g/home**");

    await page.goto("http://localhost:9000/g/home/r/test-drop-zone-recipe?edit=true");
    await page.waitForSelector("text=Instructions");
    await expect(page.getByRole("heading", { name: "Instructions" })).toHaveText("Instructions");

    await page.getByRole("button", { name: "Add" }).nth(2).click();

    await expect(page.getByRole("textbox", { name: "Step: 2" })).toBeVisible();
    await expect(page.getByText("Attach images by dragging &").first()).toContainText("Attach images by dragging");
    expect(errors).toHaveLength(0);
});
