// Generated by Skyramp v1.3.37 on 2026-08-09 04:30:39.01560629 +0000 UTC m=+2195.829482508
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output foods_bulk_assign_label_success_toast.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/foods_bulk_assign_label_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(3865000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.waitForTimeout(3000);
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);
    await page.goto("http://localhost:9000/group/data/foods");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    const emptyState = page.getByRole('row', { name: 'No data available' });
    if (await emptyState.isVisible().catch(() => false)) {
        await page.getByRole("button", { name: "Seed" }).click();
        await page.getByRole("button", { name: "Confirm" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(11066);
    }

    await page.waitForTimeout(5000);
    await page.goto("http://localhost:9000/group/data/labels");
    const existingTestLabel = page.getByText("Test Label");
    if (!await existingTestLabel.isVisible().catch(() => false)) {
        await page.getByRole("main").getByRole("button", { name: "Create" }).click();

        const playwrightRequest0: Record<string, any> = {"name": "Test Label"};

        await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
        // Wait to finish any potential hydration
        await page.waitForTimeout(1500);
        const responsePromise0 = page.waitForResponse("**/api/groups/labels**");
        await page.getByRole("button", { name: "Confirm" }).click();
        const response0 = await responsePromise0;
        expect(response0.status()).toBe(201);
    }

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/foods");
    await page.waitForTimeout(3000);
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.getByText("Assign Label").click();
    await page.getByRole("combobox", { name: "Food Label" }).click();
    await page.getByRole("option", { name: "Test Label" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/foods/**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Assert success toast with data-testid="toast-text" appears after bulk-assign completes
    await page.locator('[data-testid="toast-text"]').waitFor({ state: 'visible', timeout: 25000 });
    await expect(page.locator('[data-testid="toast-text"]')).toBeVisible();

    // Wait for network activities to finish
    await page.waitForTimeout(13500);

    await page.waitForTimeout(3000);
    await expect(page.getByText("-15 of 2687")).toContainText("1-15 of 2687");
    await expect(page.getByRole('cell', { name: 'Test Label' }).first()).toHaveText('Test Label');
    expect(errors).toHaveLength(0);
});
