// Generated by Skyramp v1.3.29 on 2026-06-25 07:31:24.969665813 +0000 UTC m=+944.074372879
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output foods_delete_dialog_cancel_confirm.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/foods_delete_dialog_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(601000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    await page.goto("http://localhost:9000");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Settings").click();
    await page.getByRole("link", { name: "Data Management" }).click();
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "TestFood-skyramp"};

    await page.getByRole("textbox", { exact: true, name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/foods**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page.getByRole("cell", { name: "TestFood-skyramp" })).toBeVisible();

    await page.getByRole("button").nth(4).click();
    await page.getByRole("button", { name: "Cancel" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("button", { name: "Cancel" })).not.toBeVisible();
    await expect(page.getByRole("cell", { name: "TestFood-skyramp" })).toBeVisible();
    await page.getByRole("button").nth(4).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/foods/**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(204);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("0-0 of")).toContainText("0-0 of 0");
    expect(errors).toHaveLength(0);
});
