// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async () => {
  const page = await newSkyrampPlaywrightPage();

  // --- login ---
  await page.goto('/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('/group/data/units');
  await page.waitForTimeout(3000);

  // open the create dialog
  await page.getByRole('button', { name: 'Create' }).click();
  const dialog = page.getByRole('dialog');

  // a 1-char name is now invalid — validators.minLength(2) requires at least 2 characters
  await dialog.getByLabel('Name').fill('x');
  const confirm = dialog.getByRole('button', { name: 'Confirm' });
  await expect(dialog.getByText('Must Be At Least 2 Characters')).toBeVisible();
  await expect(confirm).toBeDisabled();

  // a 2-char name satisfies minLength(2) → submit becomes enabled
  await dialog.getByLabel('Name').fill('Cup');
  await expect(confirm).toBeEnabled();
  await confirm.click();
  await page.waitForTimeout(2000);

  // the created unit now appears in the table, confirming the submission succeeded
  await expect(page.getByRole('cell', { name: 'Cup', exact: true })).toBeVisible();
});
