// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async ({ page }) => {
  page = newSkyrampPlaywrightPage(page);

  const errors: Error[] = [];
  page.on('pageerror', (err) => errors.push(err));

  // --- login ---
  await page.goto('http://localhost:9000/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('http://localhost:9000/group/data/units');
  await page.waitForTimeout(3000);

  // toolbar exposes both the Create and the Combine affordances
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Combine' })).toBeVisible();

  // PR b3a74862: bulk-action-toolbar now carries data-testid="bulk-action-toolbar"
  await expect(page.getByTestId('bulk-action-toolbar')).toBeVisible();
  // and data-selected-count reflects how many rows are selected (0 by default)
  await expect(page.getByTestId('bulk-action-toolbar')).toHaveAttribute('data-selected-count', '0');

  // the Combine affordance opens the merge dialog
  await page.getByRole('button', { name: 'Combine' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByText('Combine Unit')).toBeVisible(); // data-pages.units.combine-unit

  expect(errors).toHaveLength(0);
});
