// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async () => {
  const page = await newSkyrampPlaywrightPage();

  // --- login ---
  await page.goto('/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('/group/data/units');
  await page.waitForTimeout(3000);

  // keyed on the field's accessible label (search.search), NOT on `.clip-width`
  const search = page.getByLabel('Search');
  await expect(search).toBeVisible();
  await search.fill('Tablespoon');
  await page.waitForTimeout(1000);

  // table still present and responding to the search (v-data-table :search)
  await expect(page.getByRole('table')).toBeVisible();
});
