// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async () => {
  const page = await newSkyrampPlaywrightPage();

  // --- login ---
  await page.goto('/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('/group/data/units');
  await page.waitForTimeout(3000);

  // open the create dialog
  await page.getByRole('button', { name: 'New' }).click();
  const dialog = page.getByRole('dialog');

  // a 1-char name is valid on base (only `required`) → submit stays enabled
  await dialog.getByLabel('Name').fill('x');
  const confirm = dialog.getByRole('button', { name: 'Confirm' });
  await expect(confirm).toBeEnabled();
  await confirm.click();
  await page.waitForTimeout(2000);
});
