// Generated by Skyramp v1.3.29 on 2026-06-25 07:45:28.403778116 +0000 UTC m=+1175.676020093
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_bulk_delete_confirm.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_bulk_delete_confirm_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(442000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/tags");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/tags");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "Name" }).fill("Test Tag One");
    const tagResponse0 = page.waitForResponse("**/api/organizers/tags**");
    await page.getByRole("button", { name: "Confirm" }).click();
    await tagResponse0;
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "Name" }).fill("Test Tag Two");
    const tagResponse1 = page.waitForResponse("**/api/organizers/tags**");
    await page.getByRole("button", { name: "Confirm" }).click();
    await tagResponse1;
    await page.getByText("1-2 of").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByText("1-2 of")).toContainText("1-2 of 2");
    await expect(page.getByRole("row")).toHaveCount(3);
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.locator(".v-list-item.v-list-item--link.v-theme--light.v-list-item--density-compact > .v-list-item__prepend").click();
    await expect(page.getByText("Are you sure you want to")).toContainText("Are you sure you want to delete the following items?");
    await expect(page.locator('[data-total-count]')).toHaveAttribute('data-total-count', '2');
    await page.getByRole("button", { name: "Confirm" }).click();
    await expect(page.getByText("0-0 of")).toContainText("0-0 of 0");
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "No data available" })).toHaveText("No data available");
    expect(errors).toHaveLength(0);
});
