// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async () => {
  const page = await newSkyrampPlaywrightPage();

  // --- login ---
  await page.goto('/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('/group/data/units');
  await page.waitForTimeout(3000);

  // toolbar exposes both the Create and the Combine affordances
  await expect(page.getByRole('button', { name: 'New' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Combine' })).toBeVisible();

  // the Combine affordance opens the merge dialog
  await page.getByRole('button', { name: 'Combine' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByText('Combine Unit')).toBeVisible(); // data-pages.units.combine-unit
});
