// Generated by Skyramp v1.3.32 on 2026-07-03 20:54:30.102242423 +0000 UTC m=+426.196990622
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group-data-foods-combine-untouched.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/foods_combine_untouched_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(154000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/foods");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/foods");
    await expect(page.getByRole("button", { name: "Combine" })).toBeVisible();
    await page.getByRole("button", { name: "Combine" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await expect(page.getByText("Combine Food")).toBeVisible();
    await expect(page.getByRole("combobox", { name: "Source Food" })).toBeVisible();
    await expect(page.getByRole("combobox", { name: "Target Food" })).toBeVisible();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
});
