// Generated by Skyramp v1.3.37 on 2026-08-09 04:09:14.600628656 +0000 UTC m=+941.315652287
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_delete_focus_restore_escape.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_delete_focus_restore_escape_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(61000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/units");
    await page.waitForTimeout(3000);
    const deleteBtn = page.getByRole("row", { name: "Select row TestUnit" }).getByRole("button").last();
    await deleteBtn.click();
    await page.keyboard.press("Escape");
    await expect(deleteBtn).toBeFocused();

    expect(errors).toHaveLength(0);
});
