// Generated by Skyramp v1.3.37 on 2026-08-09 04:08:22.173143733 +0000 UTC m=+739.140403150
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group-data-units-edit-name-minlength.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_units_edit_name_minlength_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1087000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/units");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "Teaspoon"};

    await page.getByRole("textbox", { exact: true, name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/units**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("cell", { name: "Teaspoon", exact: true })).toBeVisible();

    await page.getByRole("row", { name: "Select row Teaspoon" }).hover();
    await page.getByRole("button").nth(3).click();
    await page.getByRole("textbox", { exact: true, name: "Name" }).fill("T");

    // a 1-char name is invalid — validators.minLength(2) now also applies to the edit form's shared Name field rules
    await expect(page.getByRole("alert", { name: "Must Be At Least 2 Characters" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Confirm" })).toBeDisabled();

    const playwrightRequest1: Record<string, any> = {"name": "Tsp"};

    await page.getByRole("textbox", { exact: true, name: "Name" }).fill(getValue(playwrightRequest1, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);

    // a 2-char name satisfies minLength(2) → the alert clears and Confirm is enabled again
    await expect(page.getByRole("alert", { name: "Must Be At Least 2 Characters" })).not.toBeVisible();
    await expect(page.getByRole("button", { name: "Confirm" })).toBeEnabled();

    const responsePromise2 = page.waitForResponse("**/api/units/**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // the row now reflects the edited name, confirming the update was persisted
    await expect(page.getByRole("cell", { name: "Tsp", exact: true })).toBeVisible();
    await expect(page.getByRole("cell", { name: "Teaspoon", exact: true })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
