// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async () => {
  const page = await newSkyrampPlaywrightPage();
  const errors: Error[] = [];
  page.on('pageerror', (err) => errors.push(err));

  // --- login ---
  await page.goto('/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('/group/data/units');
  await page.waitForTimeout(3000);

  // open the create dialog
  await page.getByRole('button', { name: 'Create' }).click();
  const dialog = page.getByRole('dialog');

  // a 1-char name is valid on base (only `required`) → submit stays enabled
  await dialog.getByLabel('Name').fill('x');
  const confirm = dialog.getByRole('button', { name: 'Confirm' });
  await expect(confirm).toBeEnabled();
  await confirm.click();
  await page.waitForTimeout(2000);

  // Verify the newly created row carries the stable data-row-id attribute added by this PR
  const createdRow = page.locator('tr[data-row-id]').first();
  await expect(createdRow).toBeVisible();
  await expect(createdRow).toHaveAttribute('data-row-id', /.+/);

  expect(errors).toHaveLength(0);
});
