// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

test('testUi', async ({ page }) => {
  page = newSkyrampPlaywrightPage(page);

  const errors: Error[] = [];
  page.on('pageerror', (err) => errors.push(err));

  // --- login ---
  await page.goto('/login');
  await page.fill('#username', 'admin@mealie.test');
  await page.fill('#password', 'MyPassword');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(3000);

  // --- navigate to the Units group-data admin page ---
  await page.goto('/group/data/units');
  await page.waitForTimeout(3000);

  // keyed on the field's accessible label (search.search), NOT on `.clip-width`
  const search = page.getByLabel('Search');
  await expect(search).toBeVisible();
  await search.fill('xyznonexistentunit99999');
  await page.waitForTimeout(1000);

  // table still present and responding to the search (v-data-table :search)
  await expect(page.getByRole('table')).toBeVisible();

  // PR: CrudTable now shows data-testid="crud-search-no-match" when search is
  // active and the full dataset is non-empty but no row matches the query.
  await expect(page.getByTestId('crud-search-no-match')).toBeVisible();

  expect(errors).toHaveLength(0);
});
