// Generated by Skyramp v1.3.37 on 2026-08-09 04:11:25.81669072 +0000 UTC m=+965.316528166
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_labels_bulk_delete_dialog_rollup.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_labels_bulk_delete_dialog_rollup_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1164000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/labels");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("button", { name: "Seed" }).click();
    await page.getByRole("button", { name: "Confirm" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.locator(".v-list-item.v-list-item--link.v-theme--light.v-list-item--density-compact > .v-list-item__prepend").click();
    await expect(page.getByTestId("bulk-rollup-header")).toContainText("0 of 15 succeeded");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/groups/labels/**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("-15 of 17")).toContainText("1-15 of 17");
    expect(errors).toHaveLength(0);
});
