// Generated by Skyramp v1.3.37 on 2026-08-09 04:09:11.228616671 +0000 UTC m=+937.943640292
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_delete_dialog_testid.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_delete_dialog_testid_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(607000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/units");
    const existingRow = page.getByRole("row", { name: "Select row TestUnit" });
    if (!(await existingRow.isVisible().catch(() => false))) {
        await page.getByRole("main").getByRole("button", { name: "Create" }).click();
        const playwrightRequest0: Record<string, any> = {"name": "TestUnit"};
        await page.getByRole("textbox", { exact: true, name: "Name" }).fill(getValue(playwrightRequest0, "name"));
        // Wait to finish any potential hydration
        await page.waitForTimeout(1500);
        const responsePromise0 = page.waitForResponse("**/api/units**");
        await page.getByRole("button", { name: "Confirm" }).click();
        const response0 = await responsePromise0;
        expect(response0.status()).toBe(201);
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await page.getByRole("row", { name: "Select row TestUnit" }).hover();
    await page.getByRole("row", { name: "Select row TestUnit" }).getByRole("button").last().click();
    await expect(page.locator('[data-testid="confirm-delete-dialog"]')).toBeVisible();
    await page.evaluate(() => { const dialog = document.querySelector('[data-testid="confirm-delete-dialog"]'); return dialog ? dialog.getAttribute('data-testid') : 'NOT FOUND'; });
    await expect(page.getByRole("paragraph")).toContainText("TestUnit");
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.locator('[data-testid="confirm-delete-dialog"]')).not.toBeVisible();
    await expect(existingRow).toBeVisible();

    expect(errors).toHaveLength(0);
});
