// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect } from "@skyramp/skyramp";

test("testUi", async ({ page }) => {
  // Login (default seeded admin)
  await page.goto("/login");
  await page.locator("#username").fill("admin@mealie.test");
  await page.locator("#password").fill("MyPassword");
  await page.getByRole("button", { name: "Login", exact: true }).click();
  await page.waitForTimeout(3000);

  // Navigate to the group-data Labels admin page
  await page.goto("/group/data/labels");
  await page.waitForTimeout(3000);

  // Observable DOM: the page title and the labels data table are present.
  await expect(page.getByText("Labels", { exact: true })).toBeVisible();
  await expect(page.getByRole("table")).toBeVisible();
});
