// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC m=+420.000000000
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_foods_dialog.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_foods_dialog_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(270000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // group-data foods page hosts a create dialog backed by the shared BaseDialog shell
    await page.goto("http://localhost:9000/group/data/foods");
    await page.waitForTimeout(3000);

    // open the create dialog (BaseButton create -> createDialog = true)
    await page.getByRole("button", { name: "Create" }).first().click();
    await page.waitForTimeout(3000);

    // the shared shell renders a Vuetify v-dialog with role="dialog"
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();

    // shared shell renders the dialog title inside a toolbar title element
    await expect(dialog.locator(".v-toolbar-title")).toBeVisible();

    // shared shell confirm action (canConfirm) keyed by accessible role + label
    await expect(dialog.getByRole("button", { name: "Confirm" })).toBeVisible();

    // shared shell cancel action keyed by accessible role + label
    await expect(dialog.getByRole("button", { name: "Cancel" })).toBeVisible();

    // ESC dismiss (BaseDialog @keydown.esc -> emit cancel)
    await page.keyboard.press("Escape");
    await page.waitForTimeout(3000);
    await expect(page.getByRole("dialog")).toHaveCount(0);

    expect(errors).toHaveLength(0);
});
