// Generated by Skyramp v1.3.37 on 2026-08-09 04:06:08.638823777 +0000 UTC m=+737.927147733
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_import_clean_initial_state.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/image_import_initial_state_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/r/create/image");
    await page.waitForSelector("text=Recipe Creation");
    await expect(page).toHaveURL(/create\/image/);
    await expect(page.getByRole("heading", { name: "Recipe Creation" })).toHaveText("Recipe Creation");
    await expect(page.getByRole("button", { name: "Upload images" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
