// Generated by Skyramp v1.3.37 on 2026-08-09 04:06:10.972620986 +0000 UTC m=+740.260944945
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_import_retry_loading.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/image_import_retry_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import path from 'path';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(150000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for login redirect then navigate to image import page
    await page.waitForTimeout(2000);
    await page.goto("http://localhost:9000/g/home/r/create/image");
    await page.waitForSelector("text=Recipe Creation");
    await page.evaluate(() => {
  const origFetch = window.fetch;
  window.fetch = function(url, opts) {
    const urlStr = (typeof url === 'string') ? url : String(url);
    if (urlStr && urlStr.includes('/api/recipes/create/image')) {
      return Promise.resolve({
        ok: false, status: 422,
        headers: new Headers({'Content-Type': 'application/json'}),
        json: () => Promise.resolve({detail: 'AI processing failed'}),
        text: () => Promise.resolve('error'),
        clone: function() { return this; },
        body: null, bodyUsed: false,
        arrayBuffer: () => Promise.resolve(new ArrayBuffer(0)),
        blob: () => Promise.resolve(new Blob()),
        formData: () => Promise.resolve(new FormData())
      });
    }
    return origFetch.apply(this, arguments);
  };
  return 'fetch mocked';
});
    await page.getByText("Create Recipe from ImagesCreate a recipe by uploading images of the recipe text").locator("input[type=\"file\"]").nth(0).setInputFiles(path.join(__dirname, 'fixtures', "test-recipe.png"));
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/recipes/create/image**");
    await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).not.toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const responsePromise1 = page.waitForResponse("**/api/recipes/create/image**");
    await page.getByTestId("image-import-retry").click();
    const response1 = await responsePromise1;
    expect(response1.status()).not.toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/create\/image/);
    await expect(page.getByTestId("image-import-retry")).toContainText("general.retry");
    expect(errors).toHaveLength(0);
});
