// Generated by Skyramp v1.3.37 on 2026-08-09 04:06:06.001209973 +0000 UTC m=+735.289533939
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_import_error_alert.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/image_import_error_alert_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import path from 'path';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(880000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await page.goto("http://localhost:9000/g/home/r/create/image");
    await page.waitForSelector("text=Recipe Creation");

    await page.evaluate(() => {
  // Try to find the Vue 3 component with state.error
  function findCompWithState(vnode, depth) {
    if (!vnode || depth > 20) return null;
    const comp = vnode.component;
    if (comp && comp.setupState) {
      const s = comp.setupState;
      if (s.state && typeof s.state === 'object' && 'error' in s.state) {
        return comp;
      }
    }
    // Traverse children via subTree
    const subTree = comp?.subTree;
    if (subTree) {
      if (subTree.component) {
        const found = findCompWithState(subTree, depth + 1);
        if (found) return found;
      }
      const children = subTree.children;
      if (children) {
        const arr = Array.isArray(children) ? children : (typeof children === 'object' ? Object.values(children) : []);
        for (const child of arr) {
          if (child && (child.component || child.children)) {
            const found = findCompWithState(child, depth + 1);
            if (found) return found;
          }
        }
      }
    }
    return null;
  }

  const nuxt = document.querySelector('#__nuxt');
  if (!nuxt) return 'no #__nuxt';
  const vueApp = nuxt.__vue_app__;
  if (!vueApp) return 'no vue app';
  const rootVnode = vueApp._vnode;
  const comp = findCompWithState(rootVnode, 0);
  if (comp) {
    comp.setupState.state.error = true;
    return 'success: state.error set to true';
  }
  return 'component not found in tree';
});
    await page.evaluate(() => {
  // Try DOM element approach - Vue 3 attaches component info to DOM nodes
  function findVueCompOnEl(el) {
    const keys = Object.getOwnPropertyNames(el);
    for (const k of keys) {
      if (k.startsWith('__vue')) {
        return el[k];
      }
    }
    return null;
  }

  // Try to find component via DOM elements  
  const allEls = document.querySelectorAll('*');
  const results = [];
  for (const el of allEls) {
    const comp = findVueCompOnEl(el);
    if (comp && comp.setupState) {
      const keys = Object.keys(comp.setupState);
      if (keys.includes('state') || keys.includes('createRecipe')) {
        results.push(keys.join(','));
        // Try to set state
        if (comp.setupState.state && 'error' in comp.setupState.state) {
          comp.setupState.state.error = true;
          return 'SUCCESS: found and set state.error=true, keys=' + keys.join(',');
        }
      }
    }
  }
  return results.length > 0 ? 'found comps but no state.error: ' + results.join(' | ') : 'nothing found';
});
    await page.evaluate(() => {
  // Mock fetch to return an error for the recipe create/image endpoint
  const origFetch = window.fetch;
  window.fetch = function(url, opts) {
    const urlStr = (typeof url === 'string') ? url : (url && url.url) || String(url);
    if (urlStr && urlStr.includes('/api/recipes/create/image')) {
      return Promise.resolve({
        ok: false,
        status: 422,
        statusText: 'Unprocessable Entity',
        headers: new Headers({'Content-Type': 'application/json'}),
        json: () => Promise.resolve({detail: 'AI processing failed'}),
        text: () => Promise.resolve('AI processing failed'),
        clone: function() { return this; },
        body: null,
        bodyUsed: false,
        arrayBuffer: () => Promise.resolve(new ArrayBuffer(0)),
        blob: () => Promise.resolve(new Blob()),
        formData: () => Promise.resolve(new FormData())
      });
    }
    return origFetch.apply(this, arguments);
  };
  return 'fetch mocked for /api/recipes/create/image';
});
    await page.getByText("Create Recipe from ImagesCreate a recipe by uploading images of the recipe text").locator("input[type=\"file\"]").nth(0).setInputFiles(path.join(__dirname, 'fixtures', "test-recipe.png"));
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/recipes/create/image**");
    await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).not.toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/create\/image/);
    await expect(page.getByTestId("image-import-retry")).toContainText("general.retry");
    expect(errors).toHaveLength(0);
});
