// Generated by Skyramp v1.3.37 on 2026-08-09 04:08:56.432416389 +0000 UTC m=+809.507051252
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output labels_create_duplicate_error.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/labels_create_duplicate_error_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(850000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);
    await page.goto("http://localhost:9000/group/data/labels");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:9000/group/data/labels/");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "DuplicateTestLabel"};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/groups/labels**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(page.getByRole("row")).toHaveCount(2);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest1: Record<string, any> = {"name": "DuplicateTestLabel"};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest1, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/groups/labels**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).not.toBe(201);
    await expect(page.getByRole("dialog")).toBeVisible();

    expect(errors).toHaveLength(0);
});
