// Generated by Skyramp v1.3.29 on 2026-06-25 07:31:26.513200344 +0000 UTC m=+945.617907400
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output labels_delete_esc_dismiss.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/labels_delete_esc_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(177000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Data Management");
    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "Name" }).fill("TestLabel-skyramp");
    await page.getByRole("button", { name: "Confirm" }).click();
    await page.getByRole("cell", { name: "TestLabel-skyramp" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("cell", { name: "TestLabel-skyramp" })).toBeVisible();
    await page.getByRole("button").nth(4).click();
    await page.getByRole("button", { name: "Cancel" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("button", { name: "Cancel" })).not.toBeVisible();
    await expect(page.getByRole("cell", { name: "TestLabel-skyramp" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
