// Generated by Skyramp v1.3.29 on 2026-06-25 21:22:15.001967129 +0000 UTC m=+481.500436980
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output label_search_flow.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/label_search_flow_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(127000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:9000/group/data/labels");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("textbox", { name: "Search" }).fill("Pro");
    await expect(page.getByRole("textbox", { name: "Search" })).toHaveValue("Pro");
    await expect(page.getByRole("row")).toHaveCount(2);
    expect(errors).toHaveLength(0);
});
