// Generated by Skyramp v1.3.29 on 2026-06-25 21:22:19.51223149 +0000 UTC m=+486.010701341
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output label_select_all_flow.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/label_select_all_flow_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(86000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:9000/group/data/labels");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await expect(page.locator("main").getByRole("checkbox", { name: "Select all" })).toBeChecked();
    await expect(page.getByRole("button", { name: "Actions" })).toBeEnabled();
    expect(errors).toHaveLength(0);
});
