// Generated by Skyramp v1.3.29 on 2026-06-25 21:22:13.264618788 +0000 UTC m=+479.763088649
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output label_create_flow.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/label_create_flow_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(443000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/labels");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "Produce-" + Date.now()};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/groups/labels**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByText("1-1 of")).toHaveText("1-1 of 1");
    expect(errors).toHaveLength(0);
});
