// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect } from "@skyramp/skyramp";

test("testUi", async ({ page }) => {
  await page.goto("/login");
  await page.waitForTimeout(3000);
  // The brand title is now sourced from the `user.brand-name` i18n key
  // (<v-toolbar-title class="text-h4 text-center">{{ $t("user.brand-name") }}</v-toolbar-title>).
  // The en-US default-locale value for `user.brand-name` is "Mealie", so this
  // assertion tracks the translated value rather than a hardcoded literal.
  await expect(page.getByText("Mealie", { exact: true })).toHaveText("Mealie");
});
