// Generated by Skyramp v1.3.29 on 2026-06-25 21:23:31.011210216 +0000 UTC m=+505.680031718
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_sign_in.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/login_sign_in_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(566000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:9000/login/");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Sign in" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/\/g\/home/);
    await expect(page.getByRole("link", { name: "3e09c6e3-cc2d-4b24-9ba3-" })).toContainText("Change Me");
    expect(pageErrors).toHaveLength(0);
});
