// Generated by Skyramp v1.3.29 on 2026-06-25 21:11:37.147678152 +0000 UTC m=+465.981545445
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_brand_title_render.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/login_brand_title_render_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(397000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:9000/login/");

    await expect(page).toHaveURL(/\/login/);
    await expect(page.getByText("Mealie", { exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Login" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
