// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC
import { test, expect } from "@skyramp/skyramp";

test("testUi", async ({ page }) => {
  await page.goto("/login");
  await page.waitForTimeout(3000);
  // The brand title is a hardcoded literal in login.vue
  // (<v-toolbar-title class="text-h4 text-center">Mealie</v-toolbar-title>).
  await expect(page.getByText("Mealie", { exact: true })).toBeVisible();
});
