// Generated by Skyramp v1.3.32 on 2026-07-05 19:15:56.217176681 +0000 UTC m=+250.654392541
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output profile_welcome_heading.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/profile_welcome_heading_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(272000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/user/profile");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByTestId("profile-welcome-heading").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByTestId("profile-welcome-heading")).toHaveText("👋 Welcome, Change Me!");
    expect(pageErrors).toHaveLength(0);
});
