// Generated by Skyramp Testbot
// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({ viewport: { width: 1280, height: 900 } });

test('testUi', async ({ page }) => {
    test.setTimeout(270000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    page.setDefaultTimeout(pageTimeout);
    page = newSkyrampPlaywrightPage(page);

    // Delay the initial recipe list fetch so the skeleton placeholder state
    // (RecipeCardSection.vue: v-if="loading && !ready") is observable instead
    // of resolving before the assertion can run.
    await page.route('**/api/recipes?**', async (route) => {
        await new Promise((resolve) => setTimeout(resolve, 3000));
        await route.continue();
    });

    const recipesResponsePromise = page.waitForResponse('**/api/recipes?**');

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();

    // While the delayed fetch is in flight, the skeleton grid should render
    // in place of the (not yet loaded) recipe cards, with 8 placeholder cards
    // matching RecipeCardSection.vue's `v-for="n in 8"`.
    await expect(page.getByTestId("recipe-grid-skeleton")).toBeVisible();
    await expect(page.getByTestId("recipe-grid-skeleton").locator(".v-skeleton-loader")).toHaveCount(8);

    const recipesResponse = await recipesResponsePromise;
    expect(recipesResponse.status()).toBe(200);

    // Once the delayed response resolves, the skeleton must disappear again.
    await expect(page.getByTestId("recipe-grid-skeleton")).not.toBeVisible({ timeout: 10000 });
    await expect(page.getByTestId("explorer-search-input")).toBeVisible();
    expect(errors).toHaveLength(0);
});
