// Generated by Skyramp v1.3.29 on 2026-06-25 16:03:45.005405798 +0000 UTC m=+511.209262820
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_url_param_search_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_url_param_search_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(148000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home?search=salad");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="explorer-results-empty"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.waitForSelector("text=No results found");
    await expect(page).toHaveURL(/search=salad/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("salad");
    await expect(page.getByTestId("explorer-results-empty")).toHaveText("No results found");

    expect(errors).toHaveLength(0);
});
