// Generated by Skyramp v1.3.29 on 2026-08-09 22:32:12.337192528 +0000 UTC m=+912.820449723
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_comment_edit_switch_stale_prefill.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_comment_edit_switch_stale_prefill_trace_1.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(358000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.waitForTimeout(1500);
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("link", { name: "Testbot Comment Recipe" }).click();
    await page.getByRole("button", { name: "Edit" }).first().click();
    await expect(page.locator('textarea:not([aria-hidden="true"])').last()).toHaveValue("This recipe turned out great, thanks for sharing! Fixed a typo.");
    await page.getByRole("button", { name: "Edit" }).click();
    await expect(page.locator('textarea:not([aria-hidden="true"])').last()).toHaveValue("Adding a pinch of salt made it even better.");
    await page.getByRole("button", { name: "Cancel" }).click();
    expect(pageErrors).toHaveLength(0);
});
