// Generated by Skyramp v1.3.29 on 2026-06-25 16:07:16.790369505 +0000 UTC m=+710.639288175
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_deep_link.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_deep_link_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(495000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home?orderBy=dateUpdated");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(2000);

    // Deep link orderBy param should be preserved in the URL after login
    await expect(page).toHaveURL(/orderBy=dateUpdated/);
    // Results region exposes its state via data-state attribute (new in this PR)
    await expect(page.getByTestId("explorer-results")).toHaveAttribute("data-state", "empty");
    // Sort menu button should be present (deep link sort hydration)
    await expect(page.getByTestId("explorer-sort-menu")).toBeVisible();

    expect(errors).toHaveLength(0);
});
