// Generated by Skyramp v1.3.29 on 2026-06-25 07:05:00.000000000 +0000 UTC m=+420.000000000
// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({ viewport: { width: 1280, height: 900 } });

test('testUi', async ({ page }) => {
    test.setTimeout(270000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    page.setDefaultTimeout(pageTimeout);
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);

    // Existing explorer toolbar affordances
    await expect(page.getByTestId("explorer-search-input")).toBeVisible();
    expect(errors).toHaveLength(0);
});
