// Generated by Skyramp v1.3.29 on 2026-06-25 21:18:28.882147424 +0000 UTC m=+532.418041754
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_grid_search_url_sync.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_grid_search_clear_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(101000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home");
    await page.waitForTimeout(2000);
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("textbox", { name: "Search..." }).fill("pasta");
    await expect(page).toHaveURL(/search=pasta/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("pasta");
    await expect(page.getByRole("main")).toContainText("Recipes");
    expect(errors).toHaveLength(0);
});
