// Generated by Skyramp v1.3.29 on 2026-06-25 07:00:00.000000000 +0000 UTC m=+420.000000000
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_search_bar.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_search_bar_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(270000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // group home renders the recipe explorer search bar
    await page.goto("http://localhost:9000/g/home");
    await page.waitForTimeout(3000);

    // anchor 1: the whole search box is wrapped in a single <form class="search-box">
    const form = page.locator("form.search-box");
    await expect(form).toBeVisible();

    // anchor 2: the search text field, addressed by its data-testid
    const searchField = page.locator('[data-testid="explorer-search-input"]');
    await expect(searchField).toBeVisible();
    await searchField.locator("input").fill("soup");

    // anchor 3: the sort menu trigger, identified by its data-testid
    const sortBtn = page.getByTestId("explorer-sort-menu");
    await expect(sortBtn).toBeVisible();
    await expect(sortBtn).toContainText("Created");

    // anchor 4: explicit submit button when auto-search is off (the big search button)
    const submitBtn = page.locator(".search-button-container button[type='submit']");
    await expect(submitBtn).toBeVisible();
    await submitBtn.click();
    await page.waitForTimeout(3000);

    // anchor 5: the query is reflected in the URL (explorer URL-sync)
    await expect(page).toHaveURL(/[?&]search=soup/);

    expect(errors).toHaveLength(0);
});
