// Generated by Skyramp v1.3.29 on 2026-06-25 21:23:50.940736522 +0000 UTC m=+551.605196381
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_search_field_testid.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_search_field_testid_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(128000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);
    await expect(page.getByTestId("explorer-clear-filters")).toHaveText("Clear");
    await expect(page.getByTestId("recipe-search-field")).toBeVisible();
    await page.getByRole("textbox", { name: "Search..." }).fill("soup");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("soup");
    await expect(page).toHaveURL(/[?&]search=soup/);

    expect(errors).toHaveLength(0);
});
