// Generated by Skyramp v1.3.29 on 2026-06-25 16:09:01.684711518 +0000 UTC m=+815.533630178
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_sort_direction.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_sort_direction_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(190000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByTestId("explorer-sort-menu").click();
    await page.getByText("Sort Ascending").click();
    // Sort button still shows the active sort option ("Created")
    await expect(page.getByTestId("explorer-sort-menu")).toHaveText("Created");
    // Non-default orderDirection (asc) is written to the URL (new PR behavior)
    await expect(page).toHaveURL(/orderDirection=asc/);

    expect(errors).toHaveLength(0);
});
