// Generated by Skyramp v1.3.29 on 2026-06-25 21:22:13.796435902 +0000 UTC m=+454.460895781
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_filters.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_filters_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(691000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("textbox", { name: "Search..." }).fill("chicken");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("chicken");
    await expect(page).toHaveURL(/[?&]search=chicken/);
    await page.getByTestId("explorer-clear-filters").click();
    await expect(page).toHaveURL(/\/g\/home$/);
    await expect(page.getByTestId("recipe-search-field")).toBeVisible();
    await expect(page.getByTestId("explorer-clear-filters")).toBeVisible();

    expect(errors).toHaveLength(0);
});
