// Generated by Skyramp v1.3.29 on 2026-06-25 21:18:16.450932598 +0000 UTC m=+564.208653363
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_with_sort.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_with_sort_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(228000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("button", { name: "Categories" }).click();
    await page.keyboard.press("Escape");
    await page.getByRole("textbox", { name: "Search..." }).fill("soup");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("soup");
    await expect(page).toHaveURL(/search=soup/);
    await page.getByRole("button", { name: "Created" }).click();
    await page.locator("[role=\"listitem\"]").getByText("Created").click();
    await page.getByTestId("explorer-clear-filters").click();
    await expect(page.getByTestId("explorer-clear-filters")).toContainText("Clear");
    await expect(page).toHaveURL(/\/g\/home$/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("");
    expect(errors).toHaveLength(0);
});
