// Generated by Skyramp v1.3.32 on 2026-07-03 21:21:32.031566008 +0000 UTC m=+834.831564258
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_button_resets_sort.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_button_resets_sort_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(70000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("button", { name: "Created" }).click();
    await page.getByText("Alphabetical").click();
    await expect(page.getByRole("button", { name: "Alphabetical", exact: true })).toHaveText("Alphabetical");
    await page.getByTestId("explorer-clear-filters").click();
    await expect(page.getByRole("button", { name: "Created", exact: true })).toHaveText("Created");
    expect(errors).toHaveLength(0);
});
