// Generated by Skyramp v1.3.29 on 2026-06-25 16:02:19.374947498 +0000 UTC m=+425.578804520
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_search_clear_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_search_clear_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(190000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("textbox", { name: "Search..." }).fill("chicken");
    await page.waitForSelector("text=No results found");
    await expect(page).toHaveURL(/search=chicken/);
    await page.getByRole("button", { name: "Clear" }).click();
    await expect(page).toHaveURL(/\/g\/home$/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("");
    await expect(page.getByTestId("explorer-results-empty")).toHaveText("No results found");

    expect(errors).toHaveLength(0);
});
