// Generated by Skyramp v1.3.37 on 2026-08-09 04:03:50.759421951 +0000 UTC m=+596.349555400
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_notes_panel_hidden_no_notes.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_notes_panel_hidden_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.getByRole("textbox", { name: "Email or Username" }).fill("admin@mealie.test");
    await page.getByRole("textbox", { name: "Password" }).fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForURL("**/g/home");

    await page.goto("http://localhost:9000/g/home/r/test-recipe-no-notes");
    await page.waitForLoadState('networkidle');
    await page.getByRole("heading", { name: "Ingredients" }).waitFor({ state: 'visible', timeout: 10000 });

    await expect(page).toHaveURL(/test-recipe-no-notes/);
    await expect(page.getByRole("heading", { name: "Ingredients" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Note" })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Comments" })).toBeVisible();

    expect(errors).toHaveLength(0);
});
