// Generated by Skyramp v1.3.37 on 2026-08-09 04:10:54.313455023 +0000 UTC m=+914.456477618
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_ingredient_editor_missing_referenceid_fallback.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_ingredient_editor_fallback_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(298000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/r/test-ingredient-recipe?edit=true");
    await page.goto("http://localhost:9000/g/home");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "Test Ingredient Recipe" }).click();
    await page.evaluate(() => {
  const cells = document.querySelectorAll('[data-testid^="ingredient-cell-"]');
  return {
    count: cells.length,
    testids: Array.from(cells).map(el => el.getAttribute('data-testid')),
    usingIndex: Array.from(cells).some(el => /ingredient-cell-\d+$/.test(el.getAttribute('data-testid') || ''))
  };
});
    await expect(page.getByRole("paragraph").filter({ hasText: "1 Cup Flour" })).toContainText("1 Cup Flour");
    await page.locator("div:nth-child(4) > .v-btn").click();
    await page.evaluate(() => {
  const noteFields = document.querySelectorAll('[data-testid^="ingredient-edit-"]');
  const cellFields = document.querySelectorAll('[data-testid^="ingredient-cell-"]');
  return {
    noteTestids: Array.from(noteFields).map(el => el.getAttribute('data-testid')),
    cellTestids: Array.from(cellFields).map(el => el.getAttribute('data-testid')),
    noteCount: noteFields.length
  };
});
    await expect(page.getByRole("textbox", { name: "Notes" })).toHaveValue("1 Cup Flour");
    expect(errors).toHaveLength(0);
});
