// Generated by Skyramp v1.3.37 on 2026-08-09 04:04:25.220554384 +0000 UTC m=+612.862799430
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_search_then_clear.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_search_then_clear_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(90000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("textbox", { name: "Search..." }).fill("nonexistentrecipe");
    await expect(page).toHaveURL(/search=nonexistentrecipe/);
    await expect(page.getByText("No results found")).toBeVisible();

    await page.getByRole("button", { name: "Clear" }).click();
    await expect(page).toHaveURL(/g\/home/);
    await expect(page.getByText("No results found")).toBeVisible();

    expect(errors).toHaveLength(0);
});
