// Generated by Skyramp v1.3.29 on 2026-08-09 22:28:03.864561789 +0000 UTC m=+664.347818964
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_comment_edit_cancel_discard.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_comment_edit_cancel_discard_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(118000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.waitForTimeout(1500);
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home/r/testbot-comment-recipe");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Edit" }).nth(1).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Edit" }).nth(1).click();
    await page.locator('textarea:not([aria-hidden="true"])').last().fill("");
    await expect(page.getByRole("button", { name: "Save" })).toBeDisabled();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByText("pinch of salt")).toHaveText("Adding a pinch of salt made it even better.");
    await expect(page.getByRole("button", { name: "Save" })).toHaveCount(0);
    expect(pageErrors).toHaveLength(0);
});
