// Generated by Skyramp v1.3.37 on 2026-08-09 04:10:08.788753526 +0000 UTC m=+874.714506128
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_sort_url_sync.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_sort_url_sync_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(188000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForSelector("text=Loading Recipes", { state: "hidden" });
    await page.getByTestId("explorer-sort-menu").click();
    await page.getByText("Alphabetical").click();
    await expect(page.getByTestId("explorer-sort-menu")).toContainText("Alphabetical");
    await expect(page).toHaveURL(/orderBy=name/);
    expect(errors).toHaveLength(0);
});
