// Generated by Skyramp v1.3.37 on 2026-08-09 04:05:09.788077955 +0000 UTC m=+624.658577945
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipes_shortcut_redirect_unauthenticated.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipes_shortcut_redirect_unauth_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/recipes");
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/\/login/);
    await expect(page.getByRole("main")).toContainText("Sign in");

    expect(errors).toHaveLength(0);
});
