// Generated by Skyramp v1.3.37 on 2026-08-09 04:10:38.817791408 +0000 UTC m=+898.960814003
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_ingredient_add_unique_testid.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_ingredient_add_unique_testid_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(970000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const existingRecipe = page.getByRole('link', { name: 'Test Ingredient Recipe' });
    if (await existingRecipe.isVisible().catch(() => false)) {
        await existingRecipe.click();
        await page.locator("div:nth-child(4) > .v-btn").click();
        await page.waitForTimeout(1500);
    } else {
        await page.getByRole("button", { exact: true, name: "Create" }).click();
        await page.getByRole("link", { name: "Create Create a recipe" }).click();

        const playwrightRequest0: Record<string, any> = {"name": "Test Ingredient Recipe"};

        await page.getByRole("textbox", { name: "Recipe Name" }).fill(getValue(playwrightRequest0, "name"));
        // Wait to finish any potential hydration
        await page.waitForTimeout(1500);
        const responsePromise0 = page.waitForResponse("**/api/recipes**");
        await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
        const response0 = await responsePromise0;
        expect(response0.status()).toBe(201);

        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await page.evaluate(() => {
  const cells = document.querySelectorAll('[data-testid^="ingredient-cell-"]');
  const notes = document.querySelectorAll('[data-testid^="ingredient-edit-"]');
  return {
    cells: Array.from(cells).map(el => ({testid: el.getAttribute('data-testid'), ingredientId: el.getAttribute('data-ingredient-id')})),
    notes: Array.from(notes).map(el => ({testid: el.getAttribute('data-testid'), ingredientId: el.getAttribute('data-ingredient-id')}))
  };
});
    await page.getByRole("button", { name: "Add" }).nth(0).click();
    await page.evaluate(() => {
  const cells = document.querySelectorAll('[data-testid^="ingredient-cell-"]');
  return {
    count: cells.length,
    testids: Array.from(cells).map(el => el.getAttribute('data-testid'))
  };
});
    await expect(page.getByTestId("ingredient-edit-629b7dcf-4553-4b79-b81e-dafe405fbc4c").locator("textarea")).toHaveValue("1 Cup Flour");
    expect(errors).toHaveLength(0);
});
