// Generated by Skyramp v1.3.37 on 2026-08-09 04:11:10.287987029 +0000 UTC m=+930.431009624
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_multiple_ingredients_unique_testids.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_multiple_ingredients_testids_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(180000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "Test Ingredient Recipe" }).click();
    await page.locator("div:nth-child(4) > .v-btn").click();
    await page.getByRole("button", { name: "Add" }).nth(0).click();
    await page.evaluate(() => {
  const cells = document.querySelectorAll('[data-testid^="ingredient-cell-"]');
  const testids = Array.from(cells).map(el => el.getAttribute('data-testid'));
  const unique = new Set(testids);
  return {
    count: cells.length,
    testids: testids,
    allUnique: unique.size === testids.length
  };
});
    const firstTestId = await page.evaluate(() => { const el = document.querySelector('[data-testid^="ingredient-edit-"]'); return el ? el.getAttribute('data-testid') : ''; });
    await expect(page.locator(`[data-testid="${firstTestId}"]`).locator("textarea")).toHaveValue("1 Cup Flour");
    expect(errors).toHaveLength(0);
});
