// Generated by Skyramp v1.3.37 on 2026-08-09 04:01:07.253845047 +0000 UTC m=+513.136572543
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_grid_skeleton_on_cookbooks.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_grid_skeleton_on_favorites_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(92000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("link", { name: "Cookbooks" }).click();
    await page.locator("a[href=\"/user/b5f5c826-0344-41f7-9a12-b9f6f84316df/favorites\"]").click();
    await expect(page).toHaveURL(/favorites/);
    await expect(page.locator('[data-testid="recipe-grid-skeleton"]')).not.toBeVisible();
    expect(errors).toHaveLength(0);
});
