// Generated by Skyramp v1.3.37 on 2026-08-09 04:01:56.259865366 +0000 UTC m=+351.132618139
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_filters.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_filters_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(126000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);

    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("textbox", { name: "Search..." }).fill("soup");
    await page.waitForTimeout(1000);
    // search term is reflected in the URL by auto-search before Clear is used
    await expect(page).toHaveURL(/[?&]search=soup/);

    await page.getByRole("button", { name: "Created" }).click();
    await page.getByText("Rating").click();
    // sort order changed away from the default before Clear is used
    await expect(page.getByRole("button", { name: "Rating" })).toHaveText("Rating");

    await page.getByTestId("explorer-clear-filters").click();
    // Clear resets the search term, the URL query, and the sort order back to defaults
    await expect(page).toHaveURL(/\/g\/home$/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("");
    await expect(page.getByRole("button", { name: "Created" })).toHaveText("Created");

    expect(errors).toHaveLength(0);
});
