// Generated by Skyramp v1.3.32 on 2026-07-03 21:21:30.21551449 +0000 UTC m=+833.015512729
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_button_resets_search.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_button_resets_search_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(284000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("textbox", { name: "Search..." }).fill("soup");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("soup");
    await expect(page).toHaveURL(/[?&]search=soup/);
    await page.getByTestId("explorer-clear-filters").click();
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("");
    await expect(page).not.toHaveURL(/[?&]search=soup/);
    expect(errors).toHaveLength(0);
});
