// Generated by Skyramp v1.3.29 on 2026-06-25 21:18:17.896238604 +0000 UTC m=+565.653959369
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_url_param.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_url_param_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(73000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home?search=chicken");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Search..." }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("chicken");
    await expect(page).toHaveURL(/search=chicken/);
    await page.getByTestId("explorer-clear-filters").click();
    await expect(page).toHaveURL(/\/g\/home$/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("");
    expect(errors).toHaveLength(0);
});
