// Generated by Skyramp v1.3.29 on 2026-06-25 19:11:14.797781953 +0000 UTC m=+429.560424826
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_search_field_tags_filter.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_search_field_tags_filter_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(100000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForSelector("text=Loading Recipes", { state: "hidden" });
    await page.getByRole("button", { name: "Tags" }).click();
    await expect(page.locator("main").getByRole("button", { name: "Has All" })).toBeVisible();
    await expect(page.locator("main").getByRole("button", { name: "Has Any" })).toBeVisible();
    await expect(page.locator("main").getByRole("button", { name: "Clear Selection" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
