// Generated by Skyramp v1.3.37 on 2026-08-09 03:59:40.886466624 +0000 UTC m=+346.476600042
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_comments_panel_expand.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_comments_panel_expand_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(479000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.getByRole("textbox", { name: "Email or Username" }).fill("admin@mealie.test");
    await page.getByRole("textbox", { name: "Password" }).fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.evaluate(async () => {
        const loginRes = await fetch('/api/auth/token', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: 'username=admin@mealie.test&password=MyPassword'
        });
        const loginData = await loginRes.json();
        const token = loginData.access_token;
        const getRes = await fetch('/api/recipes/test-recipe-with-notes', {
            headers: { 'Authorization': `Bearer ${token}` }
        });
        const recipe = await getRes.json();
        if (!recipe.notes || recipe.notes.length === 0) {
            await fetch('/api/recipes/test-recipe-with-notes', {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                body: JSON.stringify({ ...recipe, notes: [{ title: 'Preparation Tip', text: 'Make sure to preheat the oven before starting.' }] })
            });
        }
    });

    await page.goto("http://localhost:9000/g/home/r/test-recipe-with-notes");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Comments" }).waitFor({ state: 'visible', timeout: 10000 });

    await page.getByRole("button", { name: "Comments" }).click();

    await expect(page.getByRole("textbox", { name: "Join the Conversation" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Comments" })).toHaveAttribute("aria-expanded", "true");

    expect(errors).toHaveLength(0);
});
