// Generated by Skyramp v1.3.29 on 2026-06-25 21:18:14.94640836 +0000 UTC m=+562.704129135
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_clear_search_text.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_clear_search_text_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(527000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page).toHaveURL(/\/g\/home/);

    await page.getByRole("textbox", { name: "Search..." }).fill("pasta");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("pasta");
    await expect(page).toHaveURL(/search=pasta/);
    await page.getByTestId("explorer-clear-filters").click();
    await expect(page).toHaveURL(/\/g\/home$/);
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("");
    expect(errors).toHaveLength(0);
});
