// Generated by Skyramp v1.3.37 on 2026-08-09 04:01:04.188077888 +0000 UTC m=+510.070805395
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_grid_skeleton_after_search.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_grid_skeleton_after_search_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(571000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.waitForTimeout(3000);
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForTimeout(3000);
    await page.evaluate(() => { const el = document.querySelector('[data-testid="recipe-grid-skeleton"]'); return el ? window.getComputedStyle(el).display : 'not-found'; });
    await expect(page.locator('[data-testid="recipe-grid-skeleton"]')).not.toBeVisible();
    await page.getByRole("textbox", { name: "Search..." }).fill("chicken");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("chicken");
    await expect(page).toHaveURL(/search=chicken/);
    expect(errors).toHaveLength(0);
});
