// Generated by Skyramp v1.3.29 on 2026-08-09 22:27:54.226560108 +0000 UTC m=+654.709817282
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_comment_edit_save.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_comment_edit_save_trace.zip

// Import of required libraries
import { test, checkRequestPayload, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(346000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Expected request payloads for network assertions
    const expectedPayload1 = {"text": "This recipe turned out great, thanks for sharing! Fixed a typo."};

    await page.goto("http://localhost:9000/login");
    await page.waitForTimeout(2000);
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { exact: true, name: "Create" }).click();
    await page.getByRole("link", { name: "Create Create a recipe" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "Testbot Comment Recipe"};

    await page.getByRole("textbox", { name: "Recipe Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/recipes**");
    await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
    const response0 = await responsePromise0;

    const responsePromise1 = page.waitForResponse("**/api/recipes/**");
    await page.getByRole("button", { name: "Save" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest1: Record<string, any> = {"text": "This recipe turned out great, thanks for sharing!"};

    await page.getByRole("textbox", { name: "Join the Conversation" }).fill(getValue(playwrightRequest1, "text"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/comments**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest2: Record<string, any> = {"text": "Adding a pinch of salt made it even better."};

    await page.getByRole("textbox", { name: "Join the Conversation" }).fill(getValue(playwrightRequest2, "text"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/comments**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response3 = await responsePromise3;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Edit" }).first().click();

    const playwrightRequest3: Record<string, any> = {"text": "This recipe turned out great, thanks for sharing! Fixed a typo."};

    await page.locator('textarea:not([aria-hidden="true"])').last().fill(getValue(playwrightRequest3, "text"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise4 = page.waitForResponse("**/api/comments/**");
    await page.getByRole("button", { name: "Save" }).click();
    const response4 = await responsePromise4;
    // Validate request payload
    checkRequestPayload(response4.request().postDataJSON(), expectedPayload1);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("thanks for sharing")).toHaveText("This recipe turned out great, thanks for sharing! Fixed a typo.");
    await expect(page.getByRole("button", { name: "Save" })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Edit" }).first()).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
