// Generated by Skyramp v1.3.37 on 2026-08-09 04:06:06.096197445 +0000 UTC m=+648.657161552
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output shopping_list_label_reorder_save.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_label_reorder_save_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(81000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByRole("link", { name: "Shopping Lists" }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole("button").nth(4).click();
    await page.getByText("Reorder Labels").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Reorder Labels").click();
    await page.getByRole("button", { name: "Save" }).click();
    await expect(page.getByRole("button", { name: "Save" })).not.toBeVisible();
    await expect(page.getByRole("link", { name: "Shopping Lists" })).toBeVisible();
    await expect(errors).toHaveLength(0);
});
