// Generated by Skyramp v1.3.37 on 2026-08-09 04:06:01.765623775 +0000 UTC m=+644.326587892
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output shopping_list_label_reorder_dialog_open.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_label_reorder_dialog_open_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(669000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/shopping-lists");
    const existingList = page.getByRole("link", { name: "Test Shopping List" });
    if (await existingList.isVisible().catch(() => false)) {
        await existingList.click();
    } else {
        await page.getByRole("main").getByRole("button", { name: "Create" }).click();
        await page.getByRole("textbox", { name: "New List" }).fill("Test Shopping List");
        await page.getByRole("dialog").getByRole("button", { name: "Create" }).click();
    }
    await page.waitForLoadState('networkidle');
    await page.getByRole("button").nth(4).click();
    await page.getByText("Reorder Labels").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Reorder Labels").click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await page.goto("http://localhost:9000/shopping-lists/cd2c59da-8914-4b87-8673-3c91b42bcc27");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button").nth(4).click();
    await page.getByText("Reorder Labels").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Reorder Labels").click();
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();
    await expect(errors).toHaveLength(0);
});
