// Generated by Skyramp v1.3.37 on 2026-08-09 04:04:58.700231717 +0000 UTC m=+686.450174485
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_bulk_action_toolbar_testid_labels.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/ui_bulk_action_toolbar_labels_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    await expect(page.getByTestId("bulk-action-toolbar")).toBeVisible();
    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "0");
    await page.evaluate(() => document.querySelector('[data-testid="bulk-action-toolbar"]')?.getAttribute('data-testid'));
    expect(errors).toHaveLength(0);
});
