// Generated by Skyramp v1.3.37 on 2026-08-09 04:04:55.149344524 +0000 UTC m=+682.899287302
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_bulk_action_select_all_count.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/ui_bulk_action_select_all_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(926000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/units");
    await page.getByRole("button", { name: "Seed" }).click();
    await page.getByRole("button", { name: "Confirm" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await page.goto("http://localhost:9000/login");
    await page.goto("http://localhost:9000/group/data/units");
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "15");
    await expect(page.getByTestId("bulk-action-toolbar")).toContainText("Actions");
    await page.evaluate(() => document.querySelector('[data-testid="bulk-action-toolbar"]')?.getAttribute('data-selected-count'));
    expect(errors).toHaveLength(0);
});
