// Generated by Skyramp v1.3.37 on 2026-08-09 04:04:57.357648608 +0000 UTC m=+685.107591377
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_bulk_action_selected_count.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/ui_bulk_action_select_one_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(90000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/units");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/units");
    await page.locator("main").getByRole("row", { name: "Select row bunch bunches" }).getByLabel("Select row").click();
    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "1");
    await page.evaluate(() => document.querySelector('[data-testid="bulk-action-toolbar"]')?.getAttribute('data-selected-count'));
    await expect(page.getByTestId("bulk-action-toolbar")).toContainText("Actions");
    expect(errors).toHaveLength(0);
});
