// Generated by Skyramp v1.3.37 on 2026-08-09 04:07:24.078661944 +0000 UTC m=+750.984898023
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_bulk_delete_items_list.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/ui_bulk_delete_dialog_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(351000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/units");
    await page.getByRole("button", { name: "Seed" }).click();
    await page.getByRole("button", { name: "Confirm" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await page.locator("main").getByRole("row", { name: "Select row bunch bunches" }).waitFor({ state: 'visible', timeout: 10000 });

    await page.locator("main").getByRole("row", { name: "Select row bunch bunches" }).getByLabel("Select row").click();
    await page.locator("main").getByRole("row", { name: "Select row can cans" }).getByLabel("Select row").click();
    await page.getByRole("button", { name: "Actions" }).click();
    await page.locator(".v-list-item.v-list-item--link.v-theme--light.v-list-item--density-compact > .v-list-item__prepend").click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await expect(page.getByRole("dialog").getByText("bunch")).toBeVisible();
    await expect(page.getByRole("dialog").getByText("can")).toBeVisible();
    await expect(page.getByText("Are you sure you want to delete the following items?")).toBeVisible();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);

    expect(errors).toHaveLength(0);
});
