// Generated by Skyramp v1.3.29 on 2026-06-25 07:35:37.074399433 +0000 UTC m=+576.568313974
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_test_cookbook_dialog.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/cookbook_dialog_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;
const errors: Error[] = [];

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(157000);

    // set default timeout for all locator/page actions in this test
    page.on('pageerror', (err) => errors.push(err));
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/cookbooks");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/g\/home/);

    await page.getByRole("link", { name: "Cookbooks" }).click();
    await expect(page).toHaveURL(/cookbooks/);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await expect(page.getByRole("textbox", { name: "Cookbook Name" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();

    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("textbox", { name: "Cookbook Name" })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
