// Generated by Skyramp v1.3.29 on 2026-06-25 07:25:44.102999113 +0000 UTC m=+631.501980016
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_test_comments.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_comments_panel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(89000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/r/testbot-collapsible-panels-recipe");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home/r/testbot-collapsible-panels-recipe");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Comments" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Comments" }).click();
    await expect(page.getByRole("textbox", { name: "Join the Conversation" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
