// Generated by Skyramp v1.3.29 on 2026-06-25 07:38:09.888729275 +0000 UTC m=+729.382643817
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_test_shopping_list_create.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_create_submit_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;
const errors: Error[] = [];

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(87000);

    // set default timeout for all locator/page actions in this test
    page.on('pageerror', (err) => errors.push(err));
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/g\/home/);

    await page.getByRole("link", { name: "Shopping Lists" }).click();
    await expect(page).toHaveURL(/shopping-lists/);
    await page.waitForLoadState('networkidle');
    await page.getByRole("main").getByRole("button", { name: "Create" }).waitFor({ state: 'visible', timeout: 10000 });

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await expect(page.getByRole("textbox", { name: "New List" })).toBeVisible();

    await page.getByRole("textbox", { name: "New List" }).fill("Skyramp Test List");
    await page.getByRole("dialog").getByRole("button", { name: "Create" }).click();
    await expect(page).toHaveURL(/\/shopping-lists\/[a-f0-9-]+/);
    await expect(page.getByRole("textbox", { name: "New List" })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
