// Generated by Skyramp v1.3.29 on 2026-06-25 07:38:38.831314122 +0000 UTC m=+440.763952613
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/base_dialog_focus_restore_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(396000);

    const errors: string[] = [];
    page.on('pageerror', err => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page).toHaveURL(/\/g\/home/);

    await page.getByRole("button", { exact: true, name: "Create" }).click();
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:9000/shopping-lists");
    await page.waitForLoadState('networkidle');
    await page.getByRole("main").getByRole("button", { name: "Create" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("textbox", { name: "New List" })).not.toBeVisible();

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("textbox", { name: "New List" })).not.toBeVisible();

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "New List" }).fill("Test List Skyramp");
    await expect(page.getByRole("textbox", { name: "New List" })).toHaveValue("Test List Skyramp");
    await page.getByTestId("base-dialog").getByRole("button", { name: "Create" }).click();
    await expect(page).toHaveURL(/\/shopping-lists\//);
    await expect(page.getByRole("heading", { name: "Test List Skyramp" })).toHaveText("Test List Skyramp");

    expect(errors).toHaveLength(0);
});
