// Generated by Skyramp v1.3.29 on 2026-06-25 07:30:39.352634729 +0000 UTC m=+278.846549270
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_dialog_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const errors: Error[] = [];

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(210000);

    // set default timeout for all locator/page actions in this test
    page.on('pageerror', (err) => errors.push(err));
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page).toHaveURL(/\/g\/home/);

    await page.getByRole("button", { exact: true, name: "Create" }).click();
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:9000/shopping-lists");
    await expect(page).toHaveURL(/shopping-lists/);

    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await expect(page.getByRole("textbox", { name: "New List" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();

    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("textbox", { name: "New List" })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
