// Generated by Skyramp v1.3.29 on 2026-06-25 21:13:13.329658767 +0000 UTC m=+514.091804908
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output units-toolbar-no-combine.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/units_toolbar_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(413000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/units");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await expect(page.getByRole("main").getByRole("button", { name: "Create" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Combine" })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
