// Generated by Skyramp v1.3.34 on 2026-07-12 05:17:04.32613615 +0000 UTC m=+434.305530418
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output unit_create_name_minlength.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/unit_create_name_minlength_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(639000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/units");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await page.goto("http://localhost:9000/group/data/units/");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { exact: true, name: "Name" }).fill("x");

    const confirmButton = page.getByRole("button", { name: "Confirm" });
    await expect(confirmButton).toBeDisabled();
    await expect(page.getByText("Must Be At Least 2 Characters")).toBeVisible();

    const playwrightRequest0: Record<string, any> = {"name": "sp"};

    await page.getByRole("textbox", { exact: true, name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    await expect(confirmButton).toBeEnabled();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/units**");
    await confirmButton.click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    const responseBody0 = await response0.json();
    expect(responseBody0.name).toBe(getValue(playwrightRequest0, "name"));
    await expect(page.getByRole("cell", { name: getValue(playwrightRequest0, "name"), exact: true })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
