// Generated by Skyramp v1.3.29 on 2026-06-25 21:13:14.848050254 +0000 UTC m=+515.610196384
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output units-create-dialog.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/units_create_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(108000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/units");
    await page.waitForLoadState('networkidle');
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { exact: true, name: "Name" }).fill("TestUnit-ci");
    await page.getByRole("button", { name: "Confirm" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByRole("button", { name: "Confirm" })).not.toBeVisible();
    await page.getByRole("textbox", { name: "Search" }).fill("TestUnit-ci");
    await page.waitForTimeout(1500);
    await page.getByRole("cell", { name: "TestUnit-ci" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("cell", { name: "TestUnit-ci" })).toHaveText("TestUnit-ci");

    expect(errors).toHaveLength(0);
});
