// Generated by Skyramp v1.3.34 on 2026-07-12 05:22:18.812280092 +0000 UTC m=+748.791674350
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output unit_edit_name_minlength.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/unit_edit_name_minlength_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(325000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:9000/group/data/units");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/units");

    // ensure the "sp" unit this test edits exists, so the test is self-contained
    const spRow = page.getByRole("row", { name: "Select row sp" });
    if (!(await spRow.isVisible().catch(() => false))) {
        await page.getByRole("main").getByRole("button", { name: "Create" }).click();
        const createDialog = page.getByRole("dialog");
        await createDialog.waitFor({ state: "visible" });
        await createDialog.getByRole("textbox", { exact: true, name: "Name" }).fill("sp");
        await createDialog.getByRole("button", { name: "Confirm" }).click();
        await createDialog.waitFor({ state: "hidden" });
        await page.waitForTimeout(1500);
    }

    await spRow.hover();
    await spRow.getByRole("button").first().click();
    const dialog = page.getByRole("dialog");
    await dialog.waitFor({ state: "visible" });
    const nameInput = dialog.getByRole("textbox", { exact: true, name: "Name" });
    await nameInput.fill("z");

    const confirmButton = dialog.getByRole("button", { name: "Confirm" });
    await expect(confirmButton).toBeDisabled();
    await expect(dialog.getByText("Must Be At Least 2 Characters")).toBeVisible();

    const playwrightRequest0: Record<string, any> = {"name": "tsp"};

    await nameInput.fill(getValue(playwrightRequest0, "name"));
    await expect(confirmButton).toBeEnabled();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/units/**");
    await confirmButton.click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);
    const responseBody0 = await response0.json();
    expect(responseBody0.name).toBe(getValue(playwrightRequest0, "name"));
    await expect(page.getByRole("cell", { name: getValue(playwrightRequest0, "name"), exact: true })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
