// Generated by Skyramp v1.3.29 on 2026-06-25 07:31:27.911756706 +0000 UTC m=+947.016463762
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output units_delete_confirm_testid.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/units_delete_confirm_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(565000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    await page.goto("http://localhost:9000/group/data/units");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Data Management");
    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.getByText("Settings").click();
    await page.getByRole("link", { name: "Data Management" }).click();
    await page.getByRole("button", { name: "Foods" }).click();
    await page.getByRole("link", { name: "Units" }).click();
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { exact: true, name: "Name" }).fill("TestUnit-skyramp");
    await page.getByRole("button", { name: "Confirm" }).click();
    await page.getByRole("cell", { name: "TestUnit-skyramp" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("cell", { name: "TestUnit-skyramp" })).toBeVisible();
    await page.getByRole("button").nth(4).click();
    await page.getByRole("paragraph").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("paragraph")).toContainText("TestUnit-skyramp");
    await expect(page.getByRole("button", { name: "Confirm" })).toBeVisible();
    await page.getByRole("button", { name: "Confirm" }).click();
    await expect(page.getByText("0-0 of")).toContainText("0-0 of 0");
    expect(errors).toHaveLength(0);
});
