// Generated by Skyramp v1.3.29 on 2026-06-25 21:10:12.27240985 +0000 UTC m=+316.089897184
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output user_profile_no_api_tokens.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/user_profile_no_api_tokens_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(456000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/user/profile");
    await page.goto("http://localhost:9000/user/profile/api-tokens");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:9000/user/profile");
    await page.waitForLoadState('networkidle');
    await page.getByRole("link", { name: "User Settings Manage your" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("link", { name: "User Settings Manage your" })).toContainText("User Settings");
    await expect(page.getByRole("heading", { name: "Personal" })).toBeVisible();
    await expect(page.locator('a[href="/user/profile/api-tokens"]')).toHaveCount(0);

    expect(errors).toHaveLength(0);
});
