// Generated by Skyramp v1.3.29 on 2026-06-25 21:13:22.315888379 +0000 UTC m=+506.133375693
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output user_profile_settings_navigation.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/user_profile_settings_navigation_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(124000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/user/profile");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/user/profile");
    await page.waitForLoadState('networkidle');
    await page.getByRole("link", { name: "User Settings Manage your" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("link", { name: "User Settings Manage your" }).click();
    await expect(page).toHaveURL("http://localhost:9000/user/profile/edit");
    await expect(page.getByRole("heading", { name: "User Settings" })).toHaveText("User Settings");
    await expect(page.getByRole("textbox", { name: "Username" })).toHaveValue("admin");
    await expect(page.getByRole("textbox", { name: "Email" })).toHaveValue("admin@mealie.test");

    expect(errors).toHaveLength(0);
});
