// Generated by Skyramp v1.3.29 on 2026-06-25 07:29:46.316030939 +0000 UTC m=+561.681862357
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_action_toolbar_single_select.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/bulk_action_toolbar_select_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(324000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/categories");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const categoryName = `TestCat-Skyramp-${Date.now()}`;
    const playwrightRequest0: Record<string, any> = {"name": categoryName};

    await page.getByRole("textbox", { name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/organizers/categories**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("cell", { name: categoryName })).toHaveText(categoryName);
    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "0");

    await page.locator("main").getByRole("checkbox", { name: "Select row" }).click();
    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "1");
    await expect(page.getByTestId("bulk-action-toolbar")).toContainText("Actions");
    expect(pageErrors).toHaveLength(0);
});
