// Generated by Skyramp v1.3.29 on 2026-06-25 07:29:49.047841938 +0000 UTC m=+564.413673336
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_action_toolbar_deselect.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/bulk_action_toolbar_deselect_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/categories");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    const deselectCatName = `TestCat-Deselect-${Date.now()}`;
    await page.getByRole("textbox", { name: "Name" }).fill(deselectCatName);
    const responsePromise = page.waitForResponse("**/api/organizers/categories**");
    await page.getByRole("button", { name: "Confirm" }).click();
    await responsePromise;
    await page.waitForTimeout(2000);

    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "0");
    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await expect(page.getByTestId("bulk-action-toolbar")).not.toBeDisabled();

    await page.locator("main").getByRole("checkbox", { name: "Select all" }).click();
    await expect(page.getByTestId("bulk-action-toolbar")).toHaveAttribute("data-selected-count", "0");
    await expect(page.getByTestId("bulk-action-toolbar")).toBeDisabled();
    expect(pageErrors).toHaveLength(0);
});
