// Generated by Skyramp v1.3.29 on 2026-06-25 07:44:29.677894087 +0000 UTC m=+799.614587059
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output drop_zone_step_edit_ui_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/drop_zone_step_edit_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(308000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);
    await page.goto("http://localhost:9000/g/home/r/testbot-drop-zone-recipe?edit=true");
    await page.waitForLoadState('networkidle');
    await page.getByRole("heading", { name: "Instructions" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("heading", { name: "Instructions" })).toBeVisible();
    await expect(page.locator('[data-upload-state="idle"]')).toHaveCount(3);
    await expect(page.getByText("Attach images by dragging &").first()).toContainText("Attach images by dragging & dropping them into the editor");
    await page.getByRole("textbox", { name: "Step:" }).fill("Mix dry ingredients");
    const saveResponse = page.waitForResponse("**/api/recipes/**");
    await page.getByRole("button", { name: "Save" }).click();
    const savedResp = await saveResponse;
    expect(savedResp.status()).toBe(200);
    await expect(page).toHaveURL(/\/g\/home\/r\/testbot-drop-zone-recipe$/);
    await expect(page.getByRole("paragraph")).toContainText("Mix dry ingredients");
    expect(errors).toHaveLength(0);
});
