// Generated by Skyramp v1.3.29 on 2026-06-25 07:32:35.416842421 +0000 UTC m=+767.527932217
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_create_label_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_create_label_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(143000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "Name" }).fill("TestLabel-Skyramp-2");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    await page.getByTestId("create-submit").click();
    await page.waitForTimeout(2000);
    await expect(page.getByRole("cell", { name: "TestLabel-Skyramp-2" })).toHaveText("TestLabel-Skyramp-2");
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("textbox", { name: "Name" })).not.toBeVisible();
    expect(errors).toHaveLength(0);
});
