// Generated by Skyramp v1.3.29 on 2026-06-25 16:18:15.000199476 +0000 UTC m=+802.433296135
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output group_data_labels_edit_success.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_labels_edit_success_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(118000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:9000/group/data/labels");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button").nth(3).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button").nth(3).click();
    await expect(page.getByRole("textbox", { name: "Name" })).toHaveValue("Test Label Alpha");
    await page.getByRole("textbox", { name: "Name" }).fill("Test Label Beta");
    const responsePromise = page.waitForResponse("**/api/groups/labels/**");
    await page.getByRole("button", { name: "Confirm" }).click();
    const response = await responsePromise;
    expect(response.status()).toBe(200);
    await expect(page.getByRole("button", { name: "Confirm" })).not.toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "Test Label Beta" })).toHaveText("Test Label Beta");
    expect(errors).toHaveLength(0);
});
