// Generated by Skyramp v1.3.29 on 2026-06-25 16:04:27.493825435 +0000 UTC m=+551.449938208
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_instruction_view_testids.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_instruction_view_testids_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(67000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home/r/testbot-recipe");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Testbot Recipe", { timeout: 30000 });
    await expect(page.getByText("Step:")).toContainText("Step: 1");
    await expect(page.locator('[data-testid^="instruction-cell-"]')).toHaveCount(1);
    await expect(page.locator('[data-testid^="instruction-cell-"]').first()).toBeVisible();
    await expect(page.locator('[data-testid^="ingredient-cell-"]')).toHaveCount(1);
    await expect(page.locator('[data-editmode="view"]')).toBeVisible();
    expect(errors).toHaveLength(0);
});
