// Generated by Skyramp v1.3.28 on 2026-06-24 23:26:28.750303688 +0000 UTC m=+594.601773900
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_search_submit.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_search_submit_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(182000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', e => errors.push(e));

    await page.goto("http://localhost:9000/g/home");
    await page.getByRole("button", { name: "Login" }).click();
    await page.locator("main").getByRole("link", { name: "I\\" }).click();
    await page.getByRole("textbox", { name: "Search..." }).fill("chicken");
    await page.getByRole("textbox", { name: "Search..." }).press("Enter");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("chicken");
    await expect(page).toHaveURL("http://localhost:9000/g/home?search=chicken");
    await expect(errors).toHaveLength(0);
});
