// Generated by Skyramp v1.3.29 on 2026-06-25 07:21:16.27367883 +0000 UTC m=+403.645021680
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_explorer_empty_state.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_explorer_empty_state_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(157000);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await expect(page).toHaveURL(/\/g\/home/);

    await page.getByRole("textbox", { name: "Search..." }).fill("XYZNONEXISTENTRECIPE");
    await expect(page.getByRole("textbox", { name: "Search..." })).toHaveValue("XYZNONEXISTENTRECIPE");
    await expect(page).toHaveURL(/search=XYZNONEXISTENTRECIPE/);
    await expect(page.getByTestId("recipe-explorer-empty")).toBeVisible();
    await expect(page.getByTestId("recipe-explorer-empty")).toContainText("No results found");

    expect(errors).toHaveLength(0);
});
