// Generated by Skyramp v1.3.29 on 2026-06-25 16:04:24.65171459 +0000 UTC m=+548.607827373
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_ingredient_view_testids.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/recipe_ingredient_view_testids_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(374000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/g/home/r/testbot-recipe");
    await page.waitForSelector("text=Testbot Recipe");
    await expect(page.getByRole("paragraph").filter({ hasText: "1 Cup Flour" })).toHaveText("1 Cup Flour");
    await expect(page.locator('[data-testid^="ingredient-cell-"]')).toHaveCount(1);
    await expect(page.locator('[data-testid^="ingredient-cell-"]').first()).toBeVisible();
    await expect(page.locator('[data-editmode="view"]')).toBeVisible();
    expect(errors).toHaveLength(0);
});
