// Generated by Skyramp v1.3.29 on 2026-06-25 16:08:50.37778429 +0000 UTC m=+805.622180773
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output reorder_labels_dialog_render.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/reorder_labels_dialog_render_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(374000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForLoadState('networkidle');

    await page.getByRole("link", { name: "Shopping Lists" }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole("main").getByRole("button", { name: "Create" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "New List" }).fill("Test List");
    await page.getByRole("dialog").getByRole("button", { name: "Create" }).click();
    await page.getByRole("button").nth(4).hover();
    await page.getByRole("button").nth(4).click();
    await page.getByText("Reorder Labels").click();
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Save" })).toBeVisible();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("button", { name: "Cancel" })).not.toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
