// Generated by Skyramp v1.3.29 on 2026-06-25 16:08:52.555942564 +0000 UTC m=+807.800339037
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output reorder_labels_save.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/reorder_labels_save_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto("http://localhost:9000/shopping-lists/19c7ebe6-d200-47b1-93a5-72de6b3d832a");
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:9000/shopping-lists/19c7ebe6-d200-47b1-93a5-72de6b3d832a");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button").nth(4).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button").nth(4).click();
    await page.getByText("Reorder Labels").click();
    await page.getByRole("button", { name: "Save" }).click();
    await expect(page.getByRole("button", { name: "Save" })).not.toBeVisible();
    await expect(page.getByRole("heading", { name: "Test List" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
