// Generated by Skyramp v1.3.29 on 2026-06-25 07:33:52.096416103 +0000 UTC m=+786.970561355
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output shopping_list_item_check_toggle.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_item_check_toggle_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(989000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/g\/home/);
    await page.goto("http://localhost:9000/shopping-lists");
    await page.waitForLoadState('networkidle');
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();
    await page.getByRole("textbox", { name: "New List" }).fill("Test Shopping List");
    await page.getByRole("dialog").getByRole("button", { name: "Create" }).click();
    await expect(page.getByRole("heading", { name: "Test Shopping List" })).toBeVisible();
    await page.locator(".v-card-actions > .v-item-group > button:nth-child(2)").click();

    const playwrightRequest0: Record<string, any> = {"name": "Apples"};

    await page.getByRole("combobox", { name: "Food" }).fill(getValue(playwrightRequest0, "name"));
    await page.getByRole("option", { name: "Apples" }).click();
    await page.waitForTimeout(1000);
    await page.getByRole("combobox", { name: "Food" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/foods**");
    await page.getByRole("combobox", { name: "Food" }).press("Enter");
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("option", { name: "Apples" }).click();
    await page.locator(".v-card-actions > .v-item-group > button:nth-child(2)").click();
    await expect(page.getByText("Apples")).toBeVisible();
    await page.locator("#checkbox-v-0-74").click();
    await expect(page.getByRole("button", { name: "One item checked" })).toBeVisible();
    await page.locator("main").getByRole("button", { name: "One item checked" }).click();
    await page.locator("#checkbox-v-0-85").click();
    await expect(page.getByRole("button", { name: "No Label" })).toBeVisible();
    await expect(page.getByRole("button", { name: "One item checked" })).not.toBeVisible();
    expect(errors).toHaveLength(0);
});
