// Generated by Skyramp v1.3.29 on 2026-06-25 07:44:24.845457941 +0000 UTC m=+1419.719603174
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output shopping_list_item_new_item.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_item_new_item_attributes_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(685000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/g\/home/);
    await page.goto("http://localhost:9000/shopping-lists/473f6ef6-db5e-4e7f-a840-58636a4133a2");
    await expect(page.getByRole("heading", { name: "Test Shopping List" })).toBeVisible();
    await page.locator("main").getByRole("combobox", { name: "Add item" }).click();
    await page.getByRole("combobox", { name: "Food" }).fill("Bananas");
    await page.getByRole("combobox", { name: "Food" }).press("Enter");
    await page.getByRole("option", { name: "Bananas" }).click();
    await page.locator(".v-card-actions > .v-item-group > button:nth-child(2)").click();
    await expect(page.getByText("Bananas").first()).toBeVisible();
    await expect(page.getByRole("button", { name: "No Label" })).toBeVisible();
    const newItemAttrs = await page.evaluate(() => {
        const containers = Array.from(document.querySelectorAll('[data-item-id]'));
        return containers.map(el => ({ itemId: el.getAttribute('data-item-id'), checked: el.getAttribute('data-checked') }));
    });
    expect(newItemAttrs.length).toBeGreaterThan(0);
    expect(newItemAttrs.every(a => a.checked === 'false')).toBe(true);
    expect(newItemAttrs.every(a => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(a.itemId ?? ''))).toBe(true);
    expect(errors).toHaveLength(0);
});
