// Generated by Skyramp v1.3.29 on 2026-06-25 07:37:38.914075299 +0000 UTC m=+1013.788220542
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output shopping_list_item_data_attributes.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/shopping_list_item_data_attributes_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(139000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/g\/home/);
    await page.goto("http://localhost:9000/shopping-lists/473f6ef6-db5e-4e7f-a840-58636a4133a2");
    await expect(page.getByRole("heading", { name: "Test Shopping List" })).toBeVisible();
    const initialAttrs = await page.evaluate(() => {
        const el = document.querySelector('[data-item-id]');
        return el ? { itemId: el.getAttribute('data-item-id'), checked: el.getAttribute('data-checked') } : null;
    });
    expect(initialAttrs).not.toBeNull();
    expect(initialAttrs?.checked).toBe('false');
    expect(initialAttrs?.itemId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
    await page.locator("#checkbox-v-0-28").click();
    await expect(page.getByRole("button", { name: "One item checked" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
