// Generated by Skyramp v1.3.29 on 2026-06-25 07:35:43.854003711 +0000 UTC m=+591.022771415
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output theme_persist_ui_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/theme_persist_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForTimeout(3000);
    await expect(page).toHaveURL(/g\/home/);
    await expect(page.locator('html')).toHaveAttribute('data-theme', /(dark|light)/);

    await page.getByText("Settings").click();
    await expect(page.getByRole('link', { name: 'User Settings' })).toBeVisible();

    await expect(errors).toHaveLength(0);
});
