// Generated by Skyramp v1.3.29 on 2026-06-25 07:32:13.830253223 +0000 UTC m=+380.999020937
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output theme_toggle_dark_light_ui_test.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/theme_toggle_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(214000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Settings").click();
    await page.getByText("Dark Mode").click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');

    await page.getByText("Settings").click();
    await page.getByText("Light Mode").click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');

    await page.getByText("Settings").click();
    await expect(page.getByText("Dark Mode")).toBeVisible();

    await expect(errors).toHaveLength(0);
});
