// Generated by Skyramp v1.3.29 on 2026-06-25 07:43:32.461022791 +0000 UTC m=+729.148625373
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_test_delete.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/crud_table_labels_delete_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(173000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.getByRole("button").nth(4).click();
    await page.getByRole("button", { name: "Confirm" }).click();
    await expect(page.getByText("0-0 of")).toHaveText("0-0 of 0");
    await expect(page.getByRole("cell", { name: "No data available" })).toHaveText("No data available");
    await expect(page.locator("tr[data-row-id]")).toHaveCount(0);
    expect(errors).toHaveLength(0);
});
