// Generated by Skyramp v1.3.29 on 2026-06-25 07:41:01.590785275 +0000 UTC m=+578.278387867
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_test_search.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/crud_table_labels_search_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(150000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/group/data/labels");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/group/data/labels");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Search" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("textbox", { name: "Search" }).fill("TestLabel");
    await expect(page.getByRole("textbox", { name: "Search" })).toHaveValue("TestLabel");
    await expect(page.getByRole("cell", { name: "TestLabel-skyramp" })).toHaveText("TestLabel-skyramp");
    await expect(page.locator("tr[data-row-id]")).toHaveCount(1);
    expect(errors).toHaveLength(0);
});
