// Generated by Skyramp v1.3.29 on 2026-06-25 07:28:09.391546764 +0000 UTC m=+501.502636580
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/mealie/mealie/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/group_data_create_food_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(512000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:9000/group/data/foods");
    await page.getByRole("main").getByRole("button", { name: "Create" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "TestFood-Skyramp-2"};

    await page.getByRole("textbox", { exact: true, name: "Name" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/foods**");
    await page.getByTestId("create-submit").click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    await expect(page.getByRole("cell", { name: "TestFood-Skyramp-2" })).toHaveText("TestFood-Skyramp-2");
    await expect(page.getByRole("row")).toHaveCount(3);
    await expect(page.getByRole("textbox", { exact: true, name: "Name" })).not.toBeVisible();
    expect(errors).toHaveLength(0);
});
