// Generated by Skyramp v1.3.29 on 2026-06-25 07:26:43.590607718 +0000 UTC m=+685.443649652
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_import_error_retry.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/mealie-frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/image_import_error_retry_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(618000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home/r/create/image");
    await page.waitForLoadState('networkidle');
    // File upload
    const fileChooserPromise0 = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Upload images" }).click();
    const fileChooser0 = await fileChooserPromise0;
    await fileChooser0.setFiles("/home/runner/work/mealie/mealie/tests/data/images/test-image-1.jpg");
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    await expect(page.getByRole("main")).toContainText("Create");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/recipes/create/image**");
    await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).not.toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("Something Went Wrong!")).toContainText("Something Went Wrong");
    await expect(page.getByTestId("image-import-retry")).toBeVisible();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/recipes/create/image**");
    await page.getByTestId("image-import-retry").click();
    const response1 = await responsePromise1;
    expect(response1.status()).not.toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("Something Went Wrong!")).toContainText("Something Went Wrong");
    await expect(page.getByTestId("image-import-retry")).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
