// Generated by Skyramp v1.3.29 on 2026-06-25 07:26:45.111141976 +0000 UTC m=+686.964183910
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_import_initial_state.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/mealie-frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/image_import_initial_state_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/r/create/image");
    await page.waitForSelector("text=Create Recipe from Images");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home/r/create/image");
    await expect(page).toHaveURL(/\/g\/home\/r\/create\/image/);
    await expect(page.getByRole("heading", { name: "Recipe Creation" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Upload images" })).toBeVisible();
    await expect(page.getByTestId("image-import-retry")).not.toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
