// Generated by Skyramp v1.3.29 on 2026-06-25 07:26:46.487799498 +0000 UTC m=+688.340841452
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_import_multi_image_error.spec.ts \
// 		--output-dir /home/runner/work/mealie/mealie/tests/skyramp/mealie-frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie/mealie/.skyramp/image_import_multi_image_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(169000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/g/home/r/create/image");
    await page.waitForSelector("text=Upload images");
    await page.goto("http://localhost:9000/login");
    await page.locator("#username").fill("admin@mealie.test");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost:9000/g/home/r/create/image");
    // File upload
    const fileChooserPromise0 = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Upload images" }).click();
    const fileChooser0 = await fileChooserPromise0;
    await fileChooser0.setFiles("/home/runner/work/mealie/mealie/tests/data/images/test-image-1.jpg");
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    // File upload
    const fileChooserPromise1 = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Upload more images" }).click();
    const fileChooser1 = await fileChooserPromise1;
    await fileChooser1.setFiles("/home/runner/work/mealie/mealie/tests/data/images/test-image-2.png");
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    await page.locator("main").getByRole("checkbox", { name: "Translate the recipe into my" }).click();
    await expect(page.locator("main").getByRole("checkbox", { name: "Translate the recipe into my" })).not.toBeChecked();
    const responsePromise0 = page.waitForResponse("**/api/recipes/create/image**");
    await page.getByRole("main").getByRole("button", { exact: true, name: "Create" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).not.toBe(200);

    await page.waitForTimeout(3000);

    await expect(page.getByText("Something Went Wrong!")).toContainText("Something Went Wrong");
    await expect(page.getByTestId("image-import-retry")).toBeVisible();
    await expect(page).toHaveURL(/\/g\/home\/r\/create\/image/);
    expect(pageErrors).toHaveLength(0);
});
